version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: codesmelling-db
    environment:
      POSTGRES_DB: codesmelling
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: codesmelling-backend
    ports:
      - "8080:8080"
    volumes:
      - ./quizzes:/app/quizzes
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: codesmelling-frontend
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  postgres-data:
  frontend_node_modules:
